import ROOT as r

f = r.TFile('RootFiles/Histos_Isolated_MCfull.root','READ')
h_mu = f.Get('h_mu')
h_tau = f.Get('h_tau')

h_mu_q2 = h_mu.ProjectionX()
h_mu_El = h_mu.ProjectionY()
h_mu_Mmiss = h_mu.ProjectionZ()

h_tau_q2 = h_tau.ProjectionX()
h_tau_El = h_tau.ProjectionY()
h_tau_Mmiss = h_tau.ProjectionZ()

f1 = r.TFile('RootFiles/DemoHistosLattice.root','READ')
h_w_mu = f1.Get('h_w_mu_mean')
h_w_tau = f1.Get('h_w_tau_mean')

h_w_mu_q2 = h_w_mu.ProjectionX()
h_w_mu_El = h_w_mu.ProjectionY()
h_w_mu_Mmiss = h_w_mu.ProjectionZ()

h_w_tau_q2 = h_w_tau.ProjectionX()
h_w_tau_El = h_w_tau.ProjectionY()
h_w_tau_Mmiss = h_w_tau.ProjectionZ()

c = r.TCanvas('c','c',1500,500)
c.Divide(3,1)
c.cd(1)
h_mu_q2.GetYaxis().SetRangeUser(0,2E5)
h_mu_q2.Draw()
h_w_mu_q2.SetLineColor(r.kRed)
h_w_mu_q2.Draw('same')
leg = r.TLegend()
leg.AddEntry(h_mu_q2,'Before correction','L')
leg.AddEntry(h_w_mu_q2,'After correction','L')
leg.Draw()
c.cd(2)
h_mu_El.GetYaxis().SetRangeUser(0,2E5)
h_mu_El.Draw()
h_w_mu_El.SetLineColor(r.kRed)
h_w_mu_El.Draw('same')
c.cd(3)
h_mu_Mmiss.GetYaxis().SetRangeUser(0,7E4)
h_mu_Mmiss.Draw()
h_w_mu_Mmiss.SetLineColor(r.kRed)
h_w_mu_Mmiss.Draw('same')

c1 = r.TCanvas('c1','c1',1500,500)
c1.Divide(3,1)
c1.cd(1)
h_tau_q2.GetYaxis().SetRangeUser(0,5E4)
h_tau_q2.Draw()
h_w_tau_q2.SetLineColor(r.kRed)
h_w_tau_q2.Draw('same')
c1.cd(2)
h_tau_El.GetYaxis().SetRangeUser(0,2E4)
h_tau_El.Draw()
h_w_tau_El.SetLineColor(r.kRed)
h_w_tau_El.Draw('same')
c1.cd(3)
h_tau_Mmiss.GetYaxis().SetRangeUser(0,2E4)
h_tau_Mmiss.Draw()
h_w_tau_Mmiss.SetLineColor(r.kRed)
h_w_tau_Mmiss.Draw('same')
