import ROOT as r

def ReadHistos(fname):
    f = r.TFile(fname,'READ')
    #Templates with no Weight dor mbody charm correction applied
    h_Lc2ch_2bd = f.Get('h_2charm-2body')
    h_Lc2ch_2bd.SetDirectory(0)
    h_Lc2ch_mbd = f.Get('h_2charm-mbody')
    h_Lc2ch_mbd.SetDirectory(0)
    h_LcSt2ch_2bd = f.Get('h_starDs-2body')
    h_LcSt2ch_2bd.SetDirectory(0)
    h_LcSt2ch_mbd = f.Get('h_starDs-mbody')
    h_LcSt2ch_mbd.SetDirectory(0)
    #templates with alpha_linear = 1
    h_Lc2ch_mbd_1pl = f.Get('h_2charm-mbody_1pl')
    h_Lc2ch_mbd_1pl.SetDirectory(0)
    h_LcSt2ch_mbd_1pl = f.Get('h_starDs-mbody_1pl')
    h_LcSt2ch_mbd_1pl.SetDirectory(0)
    #templates with alpha_linear = -1
    h_Lc2ch_mbd_1ml = f.Get('h_2charm-mbody_1ml')
    h_Lc2ch_mbd_1ml.SetDirectory(0)
    h_LcSt2ch_mbd_1ml = f.Get('h_starDs-mbody_1ml')
    h_LcSt2ch_mbd_1ml.SetDirectory(0)
    #templates with alpha_quadratic = 1
    h_Lc2ch_mbd_1pq = f.Get('h_2charm-mbody_1pq')
    h_Lc2ch_mbd_1pq.SetDirectory(0)
    h_LcSt2ch_mbd_1pq = f.Get('h_starDs-mbody_1pq')
    h_LcSt2ch_mbd_1pq.SetDirectory(0)
    #templates with alpha_quadratic = -1
    h_Lc2ch_mbd_1mq = f.Get('h_2charm-mbody_1mq')
    h_Lc2ch_mbd_1mq.SetDirectory(0)
    h_LcSt2ch_mbd_1mq = f.Get('h_starDs-mbody_1mq')
    h_LcSt2ch_mbd_1mq.SetDirectory(0)
    #templates of Lb2Lctaunu
    h_tau = f.Get('h_tau')
    h_tau.SetDirectory(0)
    #templates of Lb2Lcstartaunu
    h_startau = f.Get('h_startau')
    h_startau.SetDirectory(0)
    return h_Lc2ch_2bd, h_Lc2ch_mbd, h_LcSt2ch_2bd, h_LcSt2ch_mbd, h_Lc2ch_mbd_1pl, h_LcSt2ch_mbd_1pl, h_Lc2ch_mbd_1ml, h_LcSt2ch_mbd_1ml, h_Lc2ch_mbd_1pq, h_LcSt2ch_mbd_1pq, h_Lc2ch_mbd_1mq, h_LcSt2ch_mbd_1mq, h_tau, h_startau

def GetProjections(h):
    hx = h.ProjectionX()
    hx.GetXaxis().SetTitle('q^{2}')
    hx.SetDirectory(0)
    hy = h.ProjectionY()
    hy.GetXaxis().SetTitle('E_{l}')
    hy.SetDirectory(0)
    hz = h.ProjectionZ()
    hz.GetXaxis().SetTitle('M^{2}_{miss}')
    hz.SetDirectory(0)
    return hx, hy, hz

def ScaleHisto(h,value):
    h1 = h.Clone(h.GetName()+'_norm')
    scale = value*1./h1.Integral()
    h1.Scale(scale)
    return h1

def GetProjectionsNormalised(h, value):
    hx, hy, hz = GetProjections(h)
    hx_norm = ScaleHisto(hx,value)
    hx_norm.SetDirectory(0)
    hy_norm = ScaleHisto(hy,value)
    hy_norm.SetDirectory(0)
    hz_norm = ScaleHisto(hz,value)
    hz_norm.SetDirectory(0)
    return hx_norm, hy_norm, hz_norm


r.gStyle.SetOptStat(0)


fname = 'RootFiles/Histos_Isolated_MCfull.root'
h_Lc2ch_2bd, h_Lc2ch_mbd, h_LcSt2ch_2bd, h_LcSt2ch_mbd, h_Lc2ch_mbd_1pl, h_LcSt2ch_mbd_1pl, h_Lc2ch_mbd_1ml, h_LcSt2ch_mbd_1ml, h_Lc2ch_mbd_1pq, h_LcSt2ch_mbd_1pq, h_Lc2ch_mbd_1mq, h_LcSt2ch_mbd_1mq, h_tau, h_startau = ReadHistos(fname)

h_Lc2ch_2bd_q2, h_Lc2ch_2bd_El, h_Lc2ch_2bd_Mm = GetProjections(h_Lc2ch_2bd)
h_Lc2ch_2bd_q2_norm, h_Lc2ch_2bd_El_norm, h_Lc2ch_2bd_Mm_norm = GetProjectionsNormalised(h_Lc2ch_2bd,1.)
h_LcSt2ch_2bd_q2, h_LcSt2ch_2bd_El, h_LcSt2ch_2bd_Mm = GetProjections(h_LcSt2ch_2bd)
h_LcSt2ch_2bd_q2_norm, h_LcSt2ch_2bd_El_norm, h_LcSt2ch_2bd_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_2bd,1)
h_Lc2ch_mbd_q2, h_Lc2ch_mbd_El, h_Lc2ch_mbd_Mm = GetProjections(h_Lc2ch_mbd)
h_Lc2ch_mbd_q2_norm, h_Lc2ch_mbd_El_norm, h_Lc2ch_mbd_Mm_norm = GetProjectionsNormalised(h_Lc2ch_mbd,1.)
h_LcSt2ch_mbd_q2, h_LcSt2ch_mbd_El, h_LcSt2ch_mbd_Mm = GetProjections(h_LcSt2ch_mbd)
h_LcSt2ch_mbd_q2_norm, h_LcSt2ch_mbd_El_norm, h_LcSt2ch_mbd_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_mbd,1.)
h_Lc2ch_mbd_1pl_q2, h_Lc2ch_mbd_1pl_El, h_Lc2ch_mbd_1pl_Mm = GetProjections(h_Lc2ch_mbd_1pl)
h_Lc2ch_mbd_1pl_q2_norm, h_Lc2ch_mbd_1pl_El_norm, h_Lc2ch_mbd_1pl_Mm_norm = GetProjectionsNormalised(h_Lc2ch_mbd_1pl,1.)
h_LcSt2ch_mbd_1pl_q2, h_LcSt2ch_mbd_1pl_El, h_LcSt2ch_mbd_1pl_Mm = GetProjections(h_LcSt2ch_mbd_1pl)
h_LcSt2ch_mbd_1pl_q2_norm, h_LcSt2ch_mbd_1pl_El_norm, h_LcSt2ch_mbd_1pl_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_mbd_1pl,1.)
h_Lc2ch_mbd_1ml_q2, h_Lc2ch_mbd_1ml_El, h_Lc2ch_mbd_1ml_Mm = GetProjections(h_Lc2ch_mbd_1ml)
h_Lc2ch_mbd_1ml_q2_norm, h_Lc2ch_mbd_1ml_El_norm, h_Lc2ch_mbd_1ml_Mm_norm = GetProjectionsNormalised(h_Lc2ch_mbd_1ml,1.)
h_LcSt2ch_mbd_1ml_q2, h_LcSt2ch_mbd_1ml_El, h_LcSt2ch_mbd_1ml_Mm = GetProjections(h_LcSt2ch_mbd_1ml)
h_LcSt2ch_mbd_1ml_q2_norm, h_LcSt2ch_mbd_1ml_El_norm, h_LcSt2ch_mbd_1ml_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_mbd_1ml,1.)
h_Lc2ch_mbd_1pq_q2, h_Lc2ch_mbd_1pq_El, h_Lc2ch_mbd_1pq_Mm = GetProjections(h_Lc2ch_mbd_1pq)
h_Lc2ch_mbd_1pq_q2_norm, h_Lc2ch_mbd_1pq_El_norm, h_Lc2ch_mbd_1pq_Mm_norm = GetProjectionsNormalised(h_Lc2ch_mbd_1pq,1.)
h_LcSt2ch_mbd_1pq_q2, h_LcSt2ch_mbd_1pq_El, h_LcSt2ch_mbd_1pq_Mm = GetProjections(h_LcSt2ch_mbd_1pq)
h_LcSt2ch_mbd_1pq_q2_norm, h_LcSt2ch_mbd_1pq_El_norm, h_LcSt2ch_mbd_1pq_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_mbd_1pq,1.)
h_Lc2ch_mbd_1mq_q2, h_Lc2ch_mbd_1mq_El, h_Lc2ch_mbd_1mq_Mm = GetProjections(h_Lc2ch_mbd_1mq)
h_Lc2ch_mbd_1mq_q2_norm, h_Lc2ch_mbd_1mq_El_norm, h_Lc2ch_mbd_1mq_Mm_norm = GetProjectionsNormalised(h_Lc2ch_mbd_1mq,1.)
h_LcSt2ch_mbd_1mq_q2, h_LcSt2ch_mbd_1mq_El, h_LcSt2ch_mbd_1mq_Mm = GetProjections(h_LcSt2ch_mbd_1mq)
h_LcSt2ch_mbd_1mq_q2_norm, h_LcSt2ch_mbd_1mq_El_norm, h_LcSt2ch_mbd_1mq_Mm_norm = GetProjectionsNormalised(h_LcSt2ch_mbd_1mq,1.)
h_tau_q2, h_tau_El, h_tau_Mm = GetProjections(h_tau)
h_tau_q2_norm, h_tau_El_norm, h_tau_Mm_norm = GetProjectionsNormalised(h_tau,1.)
h_startau_q2, h_startau_El, h_startau_Mm = GetProjections(h_startau)
h_startau_q2_norm, h_startau_El_norm, h_startau_Mm_norm = GetProjectionsNormalised(h_startau,1.)

#----------- Plot
c = r.TCanvas('c','c: Comparison 2body/mbody (no weights) LcXc',1500,500)
h_Lc2ch_2bd_q2.SetLineColor(r.kBlue)
h_Lc2ch_mbd_q2.SetLineColor(r.kOrange-3)
h_Lc2ch_2bd_El.SetLineColor(r.kBlue)
h_Lc2ch_mbd_El.SetLineColor(r.kOrange-3)
h_Lc2ch_2bd_Mm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_Mm.SetLineColor(r.kOrange-3)
c.Divide(3,1)
c.cd(1)
h_Lc2ch_2bd_q2.DrawCopy('hist')
h_Lc2ch_mbd_q2.DrawCopy('hist same')
c.cd(2)
h_Lc2ch_2bd_El.DrawCopy('hist')
h_Lc2ch_mbd_El.DrawCopy('hist same')
c.cd(3)
h_Lc2ch_2bd_Mm.DrawCopy('hist')
h_Lc2ch_mbd_Mm.DrawCopy('hist same')
l = r.TLegend(0.1,0.7,0.4,0.9)
l.AddEntry(h_Lc2ch_2bd_Mm,'#Lambda_{c}X_{c} (2body)','l')
l.AddEntry(h_Lc2ch_mbd_Mm,'#Lambda_{c}X_{c} (mbody)','l')
l.Draw()

c1 = r.TCanvas('c1','c1: Comparison 2body/mbody (no weights) Lc*Xc',1500,500)
c1.Divide(3,1)
d = c1.cd(1)
d.UseCurrentStyle()
h_LcSt2ch_2bd_q2.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_q2.DrawCopy('hist')
h_LcSt2ch_mbd_q2.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_q2.DrawCopy('hist same')
d = c1.cd(2)
d.UseCurrentStyle()
h_LcSt2ch_2bd_El.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_El.DrawCopy('hist')
h_LcSt2ch_mbd_El.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_El.DrawCopy('hist same')
d = c1.cd(3)
d.UseCurrentStyle()
h_LcSt2ch_2bd_Mm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_Mm.DrawCopy('hist')
h_LcSt2ch_mbd_Mm.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_Mm.DrawCopy('hist same')
l1 = r.TLegend(0.1,0.7,0.4,0.9)
l1.AddEntry(h_LcSt2ch_2bd_Mm,'#Lambda*_{c}X_{c} (2body)','l')
l1.AddEntry(h_LcSt2ch_mbd_Mm,'#Lambda*_{c}X_{c} (mbody)','l')
l1.Draw()

c2 = r.TCanvas('c2','c2: Comparison 2body and mbody (no weights) LcXc and Lc*Xc',1500,1000)
#set colors
h_Lc2ch_2bd_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_q2_norm.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_q2_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_2bd_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_El_norm.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_El_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_2bd_Mm_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_Mm_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_Mm_norm.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_Mm_norm.SetLineColor(r.kOrange-3)
c2.Divide(3,2)
d = c2.cd(1)
d.UseCurrentStyle()
h_Lc2ch_2bd_q2_norm.GetYaxis().SetRangeUser(0,1)
h_Lc2ch_2bd_q2_norm.DrawCopy('hist')
h_LcSt2ch_2bd_q2_norm.DrawCopy('hist same')
d = c2.cd(2)
d.UseCurrentStyle()
h_Lc2ch_2bd_El_norm.GetYaxis().SetRangeUser(0,0.5)
h_Lc2ch_2bd_El_norm.DrawCopy('hist')
h_LcSt2ch_2bd_El_norm.DrawCopy('hist same')
d = c2.cd(3)
d.UseCurrentStyle()
h_Lc2ch_2bd_Mm_norm.GetYaxis().SetRangeUser(0,0.5)
h_Lc2ch_2bd_Mm_norm.DrawCopy('hist')
h_LcSt2ch_2bd_Mm_norm.DrawCopy('hist same')
l2_1 = r.TLegend(0.1,0.7,0.4,0.9)
l2_1.AddEntry(h_Lc2ch_2bd_Mm_norm,'#Lambda_{c}X_{c} (2body)','l')
l2_1.AddEntry(h_LcSt2ch_2bd_Mm_norm,'#Lambda*_{c}X_{c} (2body)','l')
l2_1.Draw()
d = c2.cd(4)
d.UseCurrentStyle()
h_Lc2ch_mbd_q2_norm.GetYaxis().SetRangeUser(0,1)
h_Lc2ch_mbd_q2_norm.DrawCopy('hist')
h_LcSt2ch_mbd_q2_norm.DrawCopy('hist same')
d = c2.cd(5)
d.UseCurrentStyle()
h_Lc2ch_mbd_El_norm.GetYaxis().SetRangeUser(0,0.5)
h_Lc2ch_mbd_El_norm.DrawCopy('hist')
h_LcSt2ch_mbd_El_norm.DrawCopy('hist same')
d = c2.cd(6)
d.UseCurrentStyle()
h_Lc2ch_mbd_Mm_norm.GetYaxis().SetRangeUser(0,0.6)
h_Lc2ch_mbd_Mm_norm.DrawCopy('hist')
h_LcSt2ch_mbd_Mm_norm.DrawCopy('hist same')
l2_2 = r.TLegend(0.1,0.7,0.4,0.9)
l2_2.AddEntry(h_Lc2ch_mbd_Mm_norm,'#Lambda_{c}X_{c} (2body)','l')
l2_2.AddEntry(h_LcSt2ch_mbd_Mm_norm,'#Lambda*_{c}X_{c} (2body)','l')
l2_2.Draw()

c3 = r.TCanvas('c3','c3: Comparison mbody alpha linear (top) and quadratic (bot) = +/-1 (LcXc)',1500,1000)
c3.Divide(3,2)
h_Lc2ch_mbd_1pl_q2.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1ml_q2.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pq_q2.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_q2.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pl_El.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1ml_El.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pq_El.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_El.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pl_Mm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1ml_Mm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pq_Mm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_Mm.SetLineColor(r.kOrange-3)
d = c3.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_q2.GetBinContent(h_Lc2ch_mbd_1pl_q2.GetMaximumBin()),h_Lc2ch_mbd_1ml_q2.GetBinContent(h_Lc2ch_mbd_1ml_q2.GetMaximumBin())])
h_Lc2ch_mbd_1pl_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_q2.DrawCopy('hist')
h_Lc2ch_mbd_1ml_q2.DrawCopy('hist same')
d = c3.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_El.GetBinContent(h_Lc2ch_mbd_1pl_El.GetMaximumBin()),h_Lc2ch_mbd_1ml_El.GetBinContent(h_Lc2ch_mbd_1ml_El.GetMaximumBin())])
h_Lc2ch_mbd_1pl_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_El.DrawCopy('hist')
h_Lc2ch_mbd_1ml_El.DrawCopy('hist same')
d = c3.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_Mm.GetBinContent(h_Lc2ch_mbd_1pl_Mm.GetMaximumBin()),h_Lc2ch_mbd_1ml_Mm.GetBinContent(h_Lc2ch_mbd_1ml_Mm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_Mm.DrawCopy('hist')
h_Lc2ch_mbd_1ml_Mm.DrawCopy('hist same')
l3_1 = r.TLegend(0.1,0.7,0.4,0.9)
l3_1.AddEntry(h_Lc2ch_mbd_1pl_Mm,'#alpha_{linear} = +1','l')
l3_1.AddEntry(h_Lc2ch_mbd_1ml_Mm,'#alpha_{linear} = -1','l')
l3_1.SetTextSize(0.04)
l3_1.Draw()
d = c3.cd(4)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_q2.GetBinContent(h_Lc2ch_mbd_1pq_q2.GetMaximumBin()),h_Lc2ch_mbd_1mq_q2.GetBinContent(h_Lc2ch_mbd_1mq_q2.GetMaximumBin())])
h_Lc2ch_mbd_1pq_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_q2.DrawCopy('hist')
h_Lc2ch_mbd_1mq_q2.DrawCopy('hist same')
d = c3.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_El.GetBinContent(h_Lc2ch_mbd_1pq_El.GetMaximumBin()),h_Lc2ch_mbd_1mq_El.GetBinContent(h_Lc2ch_mbd_1mq_El.GetMaximumBin())])
h_Lc2ch_mbd_1pq_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_El.DrawCopy('hist')
h_Lc2ch_mbd_1mq_El.DrawCopy('hist same')
d = c3.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_Mm.GetBinContent(h_Lc2ch_mbd_1pq_Mm.GetMaximumBin()),h_Lc2ch_mbd_1mq_Mm.GetBinContent(h_Lc2ch_mbd_1mq_Mm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_Mm.DrawCopy('hist')
h_Lc2ch_mbd_1mq_Mm.DrawCopy('hist same')
l3_2 = r.TLegend(0.1,0.7,0.4,0.9)
l3_2.AddEntry(h_Lc2ch_mbd_1pq_Mm,'#alpha_{quadratic} = +1','l')
l3_2.AddEntry(h_Lc2ch_mbd_1mq_Mm,'#alpha_{quadratic} = -1','l')
l3_2.SetTextSize(0.04)
l3_2.Draw()

c4 = r.TCanvas('c4','c4: Comparison mbody alpha linear (top) and quadratic (bot) = +/-1 (LcStXc)',1500,1000)
c4.Divide(3,2)
h_LcSt2ch_mbd_1pl_q2.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_q2.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_1pq_q2.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_1pl_El.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_El.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_1pq_El.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_1pl_Mm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_Mm.SetLineColor(r.kOrange-3)
h_LcSt2ch_mbd_1pq_Mm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm.SetLineColor(r.kOrange-3)
d = c4.cd(1)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_q2.GetBinContent(h_LcSt2ch_mbd_1pl_q2.GetMaximumBin()),h_LcSt2ch_mbd_1ml_q2.GetBinContent(h_LcSt2ch_mbd_1ml_q2.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_q2.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_q2.DrawCopy('hist same')
d = c4.cd(2)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_El.GetBinContent(h_LcSt2ch_mbd_1pl_El.GetMaximumBin()),h_LcSt2ch_mbd_1ml_El.GetBinContent(h_LcSt2ch_mbd_1ml_El.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_El.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_El.DrawCopy('hist same')
d = c4.cd(3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_Mm.GetBinContent(h_LcSt2ch_mbd_1pl_Mm.GetMaximumBin()),h_LcSt2ch_mbd_1ml_Mm.GetBinContent(h_LcSt2ch_mbd_1ml_Mm.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_Mm.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_Mm.DrawCopy('hist same')
l4_1 = r.TLegend(0.1,0.7,0.4,0.9)
l4_1.AddEntry(h_LcSt2ch_mbd_1pl_Mm,'#alpha_{linear} = +1','l')
l4_1.AddEntry(h_LcSt2ch_mbd_1ml_Mm,'#alpha_{linear} = -1','l')
l4_1.SetTextSize(0.04)
l4_1.Draw()
d = c4.cd(4)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_q2.GetBinContent(h_LcSt2ch_mbd_1pl_q2.GetMaximumBin()),h_LcSt2ch_mbd_1mq_q2.GetBinContent(h_LcSt2ch_mbd_1ml_q2.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_q2.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_q2.DrawCopy('hist same')
d = c4.cd(5)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_El.GetBinContent(h_LcSt2ch_mbd_1pl_El.GetMaximumBin()),h_LcSt2ch_mbd_1mq_El.GetBinContent(h_LcSt2ch_mbd_1ml_El.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_El.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_El.DrawCopy('hist same')
d = c4.cd(6)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_Mm.GetBinContent(h_LcSt2ch_mbd_1pl_Mm.GetMaximumBin()),h_LcSt2ch_mbd_1mq_Mm.GetBinContent(h_LcSt2ch_mbd_1ml_Mm.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_Mm.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_Mm.DrawCopy('hist same')
l4_1 = r.TLegend(0.1,0.7,0.4,0.9)
l4_1.AddEntry(h_LcSt2ch_mbd_1pq_Mm,'#alpha_{quadratic} = +1','l')
l4_1.AddEntry(h_LcSt2ch_mbd_1mq_Mm,'#alpha_{quadratic} = -1','l')
l4_1.SetTextSize(0.04)
l4_1.Draw()

c5 = r.TCanvas('c5','c5: Comparison mbody alpha linear = + (top)/-1(bot)',1500,1000)
c5.Divide(3,2)
h_Lc2ch_mbd_1pl_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pl_q2_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1ml_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_q2_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pl_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pl_El_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1ml_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_El_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pl_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pl_Mm_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1ml_Mm_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1ml_Mm_norm.SetLineColor(r.kOrange-3)
d = c5.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_q2_norm.GetBinContent(h_Lc2ch_mbd_1pl_q2_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pl_q2_norm.GetBinContent(h_LcSt2ch_mbd_1pl_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_q2_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pl_q2_norm.DrawCopy('hist same')
d = c5.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_El_norm.GetBinContent(h_Lc2ch_mbd_1pl_El_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pl_El_norm.GetBinContent(h_LcSt2ch_mbd_1pl_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_El_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pl_El_norm.DrawCopy('hist same')
d = c5.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_Mm_norm.GetBinContent(h_Lc2ch_mbd_1pl_Mm_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pl_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1pl_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_Mm_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pl_Mm_norm.DrawCopy('hist same')
l5_1= r.TLegend(0.1,0.7,0.4,0.9)
l5_1.AddEntry(h_Lc2ch_mbd_1pl_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{l} = +1)','l')
l5_1.AddEntry(h_LcSt2ch_mbd_1pl_Mm_norm,'#Lambda*_{c} X_{c}','l')
l5_1.SetTextSize(0.04)
l5_1.Draw()
d = c5.cd(4)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1ml_q2_norm.GetBinContent(h_Lc2ch_mbd_1ml_q2_norm.GetMaximumBin()),h_LcSt2ch_mbd_1ml_q2_norm.GetBinContent(h_LcSt2ch_mbd_1ml_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1ml_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1ml_q2_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_q2_norm.DrawCopy('hist same')
d = c5.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1ml_El_norm.GetBinContent(h_Lc2ch_mbd_1ml_El_norm.GetMaximumBin()),h_LcSt2ch_mbd_1ml_El_norm.GetBinContent(h_LcSt2ch_mbd_1ml_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1ml_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1ml_El_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_El_norm.DrawCopy('hist same')
d = c5.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1ml_Mm_norm.GetBinContent(h_Lc2ch_mbd_1ml_Mm_norm.GetMaximumBin()),h_LcSt2ch_mbd_1ml_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1ml_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1ml_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1ml_Mm_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1ml_Mm_norm.DrawCopy('hist same')
l5_2 = r.TLegend(0.1,0.7,0.4,0.9)
l5_2.AddEntry(h_Lc2ch_mbd_1ml_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{l} = +1)','l')
l5_2.AddEntry(h_LcSt2ch_mbd_1ml_Mm_norm,'#Lambda*_{c} X_{c}','l')
l5_2.SetTextSize(0.04)
l5_2.Draw()

c6 = r.TCanvas('c6','c6: Comparison mbody alpha linear = + (top)/-1(bot)',1500,1000)
c6.Divide(3,2)
h_Lc2ch_mbd_1pq_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_q2_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1mq_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pq_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_El_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1mq_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1pq_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_Mm_norm.SetLineColor(r.kOrange-3)
h_Lc2ch_mbd_1mq_Mm_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm_norm.SetLineColor(r.kOrange-3)
d = c6.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_q2_norm.GetBinContent(h_Lc2ch_mbd_1pq_q2_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pq_q2_norm.GetBinContent(h_LcSt2ch_mbd_1pq_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_q2_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pq_q2_norm.DrawCopy('hist same')
d = c6.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_El_norm.GetBinContent(h_Lc2ch_mbd_1pq_El_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pq_El_norm.GetBinContent(h_LcSt2ch_mbd_1pq_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_El_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pq_El_norm.DrawCopy('hist same')
d = c6.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_Mm_norm.GetBinContent(h_Lc2ch_mbd_1pq_Mm_norm.GetMaximumBin()),h_LcSt2ch_mbd_1pq_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1pq_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_Mm_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1pq_Mm_norm.DrawCopy('hist same')
l6_1= r.TLegend(0.1,0.7,0.4,0.9)
l6_1.AddEntry(h_Lc2ch_mbd_1pq_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{q} = +1)','l')
l6_1.AddEntry(h_LcSt2ch_mbd_1pq_Mm_norm,'#Lambda*_{c} X_{c}','l')
l6_1.SetTextSize(0.04)
l6_1.Draw()
d = c6.cd(4)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1mq_q2_norm.GetBinContent(h_Lc2ch_mbd_1mq_q2_norm.GetMaximumBin()),h_LcSt2ch_mbd_1mq_q2_norm.GetBinContent(h_LcSt2ch_mbd_1mq_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1mq_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1mq_q2_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_q2_norm.DrawCopy('hist same')
d = c6.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1mq_El_norm.GetBinContent(h_Lc2ch_mbd_1mq_El_norm.GetMaximumBin()),h_LcSt2ch_mbd_1mq_El_norm.GetBinContent(h_LcSt2ch_mbd_1mq_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1mq_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1mq_El_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_El_norm.DrawCopy('hist same')
d = c6.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1mq_Mm_norm.GetBinContent(h_Lc2ch_mbd_1mq_Mm_norm.GetMaximumBin()),h_LcSt2ch_mbd_1mq_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1mq_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1mq_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1mq_Mm_norm.DrawCopy('hist')
h_LcSt2ch_mbd_1mq_Mm_norm.DrawCopy('hist same')
l6_2 = r.TLegend(0.1,0.7,0.4,0.9)
l6_2.AddEntry(h_Lc2ch_mbd_1mq_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{q} = +1)','l')
l6_2.AddEntry(h_LcSt2ch_mbd_1mq_Mm_norm,'#Lambda*_{c} X_{c}','l')
l6_2.SetTextSize(0.04)
l6_2.Draw()

c7 = r.TCanvas('c7','c7: All comparisons together (LcXc)',1500,500)
c7.Divide(3,1)
h_Lc2ch_mbd_q2.SetMarkerStyle(8)
h_Lc2ch_mbd_q2.SetLineColor(r.kBlack)
h_Lc2ch_mbd_q2.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_q2.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_q2.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_q2.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_q2.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_q2.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_q2.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_q2.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_q2.SetLineStyle(9)
h_Lc2ch_mbd_1pq_q2.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_q2.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_q2.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_q2.SetLineStyle(9)
h_Lc2ch_mbd_1mq_q2.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_q2.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_El.SetMarkerStyle(8)
h_Lc2ch_mbd_El.SetLineColor(r.kBlack)
h_Lc2ch_mbd_El.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_El.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_El.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_El.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_El.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_El.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_El.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_El.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_El.SetLineStyle(9)
h_Lc2ch_mbd_1pq_El.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_El.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_El.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_El.SetLineStyle(9)
h_Lc2ch_mbd_1mq_El.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_El.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_Mm.SetMarkerStyle(8)
h_Lc2ch_mbd_Mm.SetLineColor(r.kBlack)
h_Lc2ch_mbd_Mm.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_Mm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_Mm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_Mm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_Mm.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_Mm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_Mm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_Mm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_Mm.SetLineStyle(9)
h_Lc2ch_mbd_1pq_Mm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_Mm.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_Mm.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_Mm.SetLineStyle(9)
h_Lc2ch_mbd_1mq_Mm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_Mm.SetMarkerColor(r.kBlue)
d = c7.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_q2.GetBinContent(h_Lc2ch_mbd_1pl_q2.GetMaximumBin()),h_Lc2ch_mbd_1pq_q2.GetBinContent(h_Lc2ch_mbd_1pq_q2.GetMaximumBin())])
h_Lc2ch_mbd_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_q2.DrawCopy('PE')
h_Lc2ch_mbd_1pl_q2.DrawCopy('PE same')
h_Lc2ch_mbd_1ml_q2.DrawCopy('PE same')
h_Lc2ch_mbd_1pq_q2.DrawCopy('PE same')
h_Lc2ch_mbd_1mq_q2.DrawCopy('PE same')
d = c7.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_El.GetBinContent(h_Lc2ch_mbd_1pl_El.GetMaximumBin()),h_Lc2ch_mbd_1pq_El.GetBinContent(h_Lc2ch_mbd_1pq_El.GetMaximumBin())])
h_Lc2ch_mbd_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_El.DrawCopy('PE')
h_Lc2ch_mbd_1pl_El.DrawCopy('PE same')
h_Lc2ch_mbd_1ml_El.DrawCopy('PE same')
h_Lc2ch_mbd_1pq_El.DrawCopy('PE same')
h_Lc2ch_mbd_1mq_El.DrawCopy('PE same')
d = c7.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_Mm.GetBinContent(h_Lc2ch_mbd_1pl_Mm.GetMaximumBin()),h_Lc2ch_mbd_1pq_Mm.GetBinContent(h_Lc2ch_mbd_1pq_Mm.GetMaximumBin())])
h_Lc2ch_mbd_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_Mm.DrawCopy('PE')
h_Lc2ch_mbd_1pl_Mm.DrawCopy('PE same')
h_Lc2ch_mbd_1ml_Mm.DrawCopy('PE same')
h_Lc2ch_mbd_1pq_Mm.DrawCopy('PE same')
h_Lc2ch_mbd_1mq_Mm.DrawCopy('PE same')
l7 = r.TLegend(0.1,0.7,0.4,0.9)
l7.AddEntry(h_Lc2ch_mbd_Mm,'nominal','lp')
l7.AddEntry(h_Lc2ch_mbd_1pl_Mm,'#alpha_{l} = +1','lp')
l7.AddEntry(h_Lc2ch_mbd_1ml_Mm,'#alpha_{l} = -1','lp')
l7.AddEntry(h_Lc2ch_mbd_1pq_Mm,'#alpha_{q} = +1','lp')
l7.AddEntry(h_Lc2ch_mbd_1mq_Mm,'#alpha_{q} = -1','lp')
l7.Draw()

c8 = r.TCanvas('c8','c8: All comparisons together (LcXc)',1500,500)
c8.Divide(3,1)
h_LcSt2ch_mbd_q2.SetMarkerStyle(8)
h_LcSt2ch_mbd_q2.SetLineColor(r.kBlack)
h_LcSt2ch_mbd_q2.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_q2.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_q2.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_q2.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_q2.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_q2.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_q2.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_q2.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_q2.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_q2.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_q2.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_q2.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_q2.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_El.SetMarkerStyle(8)
h_LcSt2ch_mbd_El.SetLineColor(r.kBlack)
h_LcSt2ch_mbd_El.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_El.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_El.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_El.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_El.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_El.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_El.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_El.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_El.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_El.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_El.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_El.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_El.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_Mm.SetMarkerStyle(8)
h_LcSt2ch_mbd_Mm.SetLineColor(r.kBlack)
h_LcSt2ch_mbd_Mm.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_Mm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_Mm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_Mm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_Mm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_Mm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_Mm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_Mm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_Mm.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_Mm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_Mm.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_Mm.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_Mm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm.SetMarkerColor(r.kBlue)
d = c8.cd(1)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_q2.GetBinContent(h_LcSt2ch_mbd_1pl_q2.GetMaximumBin()),h_LcSt2ch_mbd_1pq_q2.GetBinContent(h_LcSt2ch_mbd_1pq_q2.GetMaximumBin())])
h_LcSt2ch_mbd_q2.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_q2.DrawCopy('PE')
h_LcSt2ch_mbd_1pl_q2.DrawCopy('PE same')
h_LcSt2ch_mbd_1ml_q2.DrawCopy('PE same')
h_LcSt2ch_mbd_1pq_q2.DrawCopy('PE same')
h_LcSt2ch_mbd_1mq_q2.DrawCopy('PE same')
d = c8.cd(2)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_El.GetBinContent(h_LcSt2ch_mbd_1pl_El.GetMaximumBin()),h_LcSt2ch_mbd_1pq_El.GetBinContent(h_LcSt2ch_mbd_1pq_El.GetMaximumBin())])
h_LcSt2ch_mbd_El.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_El.DrawCopy('PE')
h_LcSt2ch_mbd_1pl_El.DrawCopy('PE same')
h_LcSt2ch_mbd_1ml_El.DrawCopy('PE same')
h_LcSt2ch_mbd_1pq_El.DrawCopy('PE same')
h_LcSt2ch_mbd_1mq_El.DrawCopy('PE same')
d = c8.cd(3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_Mm.GetBinContent(h_LcSt2ch_mbd_1pl_Mm.GetMaximumBin()),h_LcSt2ch_mbd_1pq_Mm.GetBinContent(h_LcSt2ch_mbd_1pq_Mm.GetMaximumBin())])
h_LcSt2ch_mbd_Mm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_Mm.DrawCopy('PE')
h_LcSt2ch_mbd_1pl_Mm.DrawCopy('PE same')
h_LcSt2ch_mbd_1ml_Mm.DrawCopy('PE same')
h_LcSt2ch_mbd_1pq_Mm.DrawCopy('PE same')
h_LcSt2ch_mbd_1mq_Mm.DrawCopy('PE same')
l8 = r.TLegend(0.1,0.7,0.4,0.9)
l8.AddEntry(h_LcSt2ch_mbd_Mm,'nominal','lp')
l8.AddEntry(h_LcSt2ch_mbd_1pl_Mm,'#alpha_{l} = +1','lp')
l8.AddEntry(h_LcSt2ch_mbd_1ml_Mm,'#alpha_{l} = -1','lp')
l8.AddEntry(h_LcSt2ch_mbd_1pq_Mm,'#alpha_{q} = +1','lp')
l8.AddEntry(h_LcSt2ch_mbd_1mq_Mm,'#alpha_{q} = -1','lp')
l8.Draw()

c9 = r.TCanvas('c9','c9: Comparison LcXc and Lctau (TOP: 2body, BOT: mbody)',1500,1000)
c9.Divide(3,2)
h_Lc2ch_2bd_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_2bd_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_2bd_Mm_norm.SetLineColor(r.kBlue)
h_tau_q2_norm.SetLineColor(r.kOrange-3)
h_tau_El_norm.SetLineColor(r.kOrange-3)
h_tau_Mm_norm.SetLineColor(r.kOrange-3)
d = c9.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_q2_norm.GetBinContent(h_Lc2ch_2bd_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_Lc2ch_2bd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_q2_norm.DrawCopy('hist')
h_tau_q2_norm.DrawCopy('hist same')
d = c9.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_El_norm.GetBinContent(h_Lc2ch_2bd_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_Lc2ch_2bd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_El_norm.DrawCopy('hist')
h_tau_El_norm.DrawCopy('hist same')
d = c9.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_Mm_norm.GetBinContent(h_Lc2ch_2bd_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_Lc2ch_2bd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_Mm_norm.DrawCopy('hist')
h_tau_Mm_norm.DrawCopy('hist same')
l9_1 = r.TLegend(0.1,0.7,0.4,0.9)
l9_1.AddEntry(h_Lc2ch_2bd_Mm_norm,'#Lambda_{c} X_{c} 2body')
l9_1.AddEntry(h_tau_Mm_norm,'#Lambda_{c}#tau')
l9_1.SetTextSize(0.04)
l9_1.Draw()
d = c9.cd(4)
h_Lc2ch_mbd_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_Mm_norm.SetLineColor(r.kBlue)
h_tau_q2_norm.SetLineColor(r.kOrange-3)
h_tau_El_norm.SetLineColor(r.kOrange-3)
h_tau_Mm_norm.SetLineColor(r.kOrange-3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_q2_norm.GetBinContent(h_Lc2ch_mbd_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_q2_norm.DrawCopy('hist')
h_tau_q2_norm.DrawCopy('hist same')
d = c9.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_El_norm.GetBinContent(h_Lc2ch_mbd_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_El_norm.DrawCopy('hist')
h_tau_El_norm.DrawCopy('hist same')
d = c9.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_Mm_norm.GetBinContent(h_Lc2ch_mbd_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_Mm_norm.DrawCopy('hist')
h_tau_Mm_norm.DrawCopy('hist same')
l9_2 = r.TLegend(0.1,0.7,0.4,0.9)
l9_2.AddEntry(h_Lc2ch_mbd_Mm_norm,'#Lambda_{c} X_{c} mbody','l')
l9_2.AddEntry(h_tau_Mm_norm,'#Lambda_{c}#tau','l')
l9_2.SetTextSize(0.04)
l9_2.Draw()

c10 = r.TCanvas('c10','c10: Comparison Lc*Xc and Lc*startau (TOP: 2body, BOT: mbody)',1500,1000)
c10.Divide(3,2)
h_LcSt2ch_2bd_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_Mm_norm.SetLineColor(r.kBlue)
h_startau_q2_norm.SetLineColor(r.kOrange-3)
h_startau_El_norm.SetLineColor(r.kOrange-3)
h_startau_Mm_norm.SetLineColor(r.kOrange-3)
d = c10.cd(1)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_q2_norm.GetBinContent(h_LcSt2ch_2bd_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_LcSt2ch_2bd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_q2_norm.DrawCopy('hist')
h_startau_q2_norm.DrawCopy('hist same')
d = c10.cd(2)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_El_norm.GetBinContent(h_LcSt2ch_2bd_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_LcSt2ch_2bd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_El_norm.DrawCopy('hist')
h_startau_El_norm.DrawCopy('hist same')
d = c10.cd(3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_Mm_norm.GetBinContent(h_LcSt2ch_2bd_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_2bd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_Mm_norm.DrawCopy('hist')
h_startau_Mm_norm.DrawCopy('hist same')
l10_1 = r.TLegend(0.1,0.7,0.4,0.9)
l10_1.AddEntry(h_LcSt2ch_2bd_Mm_norm,'#Lambda*_{c} X_{c} 2body','l')
l10_1.AddEntry(h_startau_Mm_norm,'#Lambda*_{c}#tau','l')
l10_1.SetTextSize(0.04)
l10_1.Draw()
d = c10.cd(4)
h_LcSt2ch_mbd_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_Mm_norm.SetLineColor(r.kBlue)
h_startau_q2_norm.SetLineColor(r.kOrange-3)
h_startau_El_norm.SetLineColor(r.kOrange-3)
h_startau_Mm_norm.SetLineColor(r.kOrange-3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_q2_norm.GetBinContent(h_LcSt2ch_mbd_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_LcSt2ch_mbd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_q2_norm.DrawCopy('hist')
h_startau_q2_norm.DrawCopy('hist same')
d = c10.cd(5)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_El_norm.GetBinContent(h_LcSt2ch_mbd_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_LcSt2ch_mbd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_El_norm.DrawCopy('hist')
h_startau_El_norm.DrawCopy('hist same')
d = c10.cd(6)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_Mm_norm.GetBinContent(h_LcSt2ch_mbd_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_mbd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_Mm_norm.DrawCopy('hist')
h_startau_Mm_norm.DrawCopy('hist same')
l10_2 = r.TLegend(0.1,0.7,0.4,0.9)
l10_2.AddEntry(h_LcSt2ch_mbd_Mm_norm,'#Lambda*_{c} X_{c} mbody','l')
l10_2.AddEntry(h_startau_Mm_norm,'#Lambda*_{c}#tau','l')
l10_2.SetTextSize(0.04)
l10_2.Draw()

c11 = r.TCanvas('c11','c11: Comparison LcXc mbody and Lctau (TOP: alpha_l, BOT: alpha_q',1500,1000)
c11.Divide(3,2)
h_tau_q2_norm.SetMarkerStyle(8)
h_tau_q2_norm.SetLineColor(r.kBlack)
h_tau_q2_norm.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_q2_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_q2_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_q2_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_q2_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_q2_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_q2_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_q2_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_q2_norm.SetLineStyle(9)
h_Lc2ch_mbd_1pq_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_q2_norm.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_q2_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_q2_norm.SetLineStyle(9)
h_Lc2ch_mbd_1mq_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_q2_norm.SetMarkerColor(r.kBlue)
h_tau_El_norm.SetMarkerStyle(8)
h_tau_El_norm.SetLineColor(r.kBlack)
h_tau_El_norm.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_El_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_El_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_El_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_El_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_El_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_El_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_El_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_El_norm.SetLineStyle(9)
h_Lc2ch_mbd_1pq_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_El_norm.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_El_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_El_norm.SetLineStyle(9)
h_Lc2ch_mbd_1mq_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_El_norm.SetMarkerColor(r.kBlue)
h_tau_Mm_norm.SetMarkerStyle(8)
h_tau_Mm_norm.SetLineColor(r.kBlack)
h_tau_Mm_norm.SetMarkerColor(r.kBlack)
h_Lc2ch_mbd_1pl_Mm_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pl_Mm_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1pl_Mm_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1ml_Mm_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1ml_Mm_norm.SetLineColor(r.kRed)
h_Lc2ch_mbd_1ml_Mm_norm.SetMarkerColor(r.kRed)
h_Lc2ch_mbd_1pq_Mm_norm.SetMarkerStyle(22)
h_Lc2ch_mbd_1pq_Mm_norm.SetLineStyle(9)
h_Lc2ch_mbd_1pq_Mm_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1pq_Mm_norm.SetMarkerColor(r.kBlue)
h_Lc2ch_mbd_1mq_Mm_norm.SetMarkerStyle(23)
h_Lc2ch_mbd_1mq_Mm_norm.SetLineStyle(9)
h_Lc2ch_mbd_1mq_Mm_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_1mq_Mm_norm.SetMarkerColor(r.kBlue)
d = c11.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_q2_norm.GetBinContent(h_Lc2ch_mbd_1pl_q2_norm.GetMaximumBin()), h_Lc2ch_mbd_1ml_q2_norm.GetBinContent(h_Lc2ch_mbd_1ml_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_q2_norm.DrawCopy('PE')
h_Lc2ch_mbd_1ml_q2_norm.DrawCopy('PE same')
h_tau_q2_norm.DrawCopy('PE hist same')
d = c11.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_El_norm.GetBinContent(h_Lc2ch_mbd_1pl_El_norm.GetMaximumBin()), h_Lc2ch_mbd_1ml_El_norm.GetBinContent(h_Lc2ch_mbd_1ml_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_El_norm.DrawCopy('PE')
h_Lc2ch_mbd_1ml_El_norm.DrawCopy('PE same')
h_tau_El_norm.DrawCopy('PE hist same')
d = c11.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pl_Mm_norm.GetBinContent(h_Lc2ch_mbd_1pl_Mm_norm.GetMaximumBin()), h_Lc2ch_mbd_1ml_Mm_norm.GetBinContent(h_Lc2ch_mbd_1ml_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pl_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pl_Mm_norm.DrawCopy('PE')
h_Lc2ch_mbd_1ml_q2_norm.DrawCopy('PE same')
h_tau_Mm_norm.DrawCopy('PE hist same')
l11_1 = r.TLegend(0.1,0.7,0.4,0.9)
l11_1.AddEntry(h_tau_Mm_norm,'#Lambda_{c} #tau','lP')
l11_1.AddEntry(h_Lc2ch_mbd_1pl_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{l} = 1)','lP')
l11_1.AddEntry(h_Lc2ch_mbd_1ml_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{l} = -1)','lP')
l11_1.Draw()
d = c11.cd(4)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_q2_norm.GetBinContent(h_Lc2ch_mbd_1pq_q2_norm.GetMaximumBin()), h_Lc2ch_mbd_1mq_q2_norm.GetBinContent(h_Lc2ch_mbd_1mq_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_q2_norm.DrawCopy('PE')
h_Lc2ch_mbd_1mq_q2_norm.DrawCopy('PE same')
h_tau_q2_norm.DrawCopy('PE hist same')
d = c11.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_El_norm.GetBinContent(h_Lc2ch_mbd_1pq_El_norm.GetMaximumBin()), h_Lc2ch_mbd_1mq_El_norm.GetBinContent(h_Lc2ch_mbd_1mq_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_El_norm.DrawCopy('PE')
h_Lc2ch_mbd_1mq_El_norm.DrawCopy('PE same')
h_tau_El_norm.DrawCopy('PE hist same')
d = c11.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_1pq_Mm_norm.GetBinContent(h_Lc2ch_mbd_1pq_Mm_norm.GetMaximumBin()), h_Lc2ch_mbd_1mq_Mm_norm.GetBinContent(h_Lc2ch_mbd_1mq_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_1pq_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_1pq_Mm_norm.DrawCopy('PE')
h_Lc2ch_mbd_1mq_q2_norm.DrawCopy('PE same')
h_tau_Mm_norm.DrawCopy('PE hist same')
l11_2 = r.TLegend(0.1,0.7,0.4,0.9)
l11_2.AddEntry(h_tau_Mm_norm,'#Lambda_{c} #tau','lP')
l11_2.AddEntry(h_Lc2ch_mbd_1pq_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{q} = 1)','lP')
l11_2.AddEntry(h_Lc2ch_mbd_1mq_Mm_norm,'#Lambda_{c} X_{c} (#alpha_{q} = -1)','lP')
l11_2.Draw()

c12 = r.TCanvas('c12','c12: Comparison Lc*Xc mbody and Lcstartau (TOP: alpha_l, BOT: alpha_q',1500,1000)
c12.Divide(3,2)
h_startau_q2_norm.SetMarkerStyle(8)
h_startau_q2_norm.SetLineColor(r.kBlack)
h_startau_q2_norm.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_q2_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_q2_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_q2_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_q2_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_q2_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_q2_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_q2_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_q2_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_q2_norm.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_q2_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_q2_norm.SetMarkerColor(r.kBlue)
h_startau_El_norm.SetMarkerStyle(8)
h_startau_El_norm.SetLineColor(r.kBlack)
h_startau_El_norm.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_El_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_El_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_El_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_El_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_El_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_El_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_El_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_El_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_El_norm.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_El_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_El_norm.SetMarkerColor(r.kBlue)
h_startau_Mm_norm.SetMarkerStyle(8)
h_startau_Mm_norm.SetLineColor(r.kBlack)
h_startau_Mm_norm.SetMarkerColor(r.kBlack)
h_LcSt2ch_mbd_1pl_Mm_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pl_Mm_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1pl_Mm_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1ml_Mm_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1ml_Mm_norm.SetLineColor(r.kRed)
h_LcSt2ch_mbd_1ml_Mm_norm.SetMarkerColor(r.kRed)
h_LcSt2ch_mbd_1pq_Mm_norm.SetMarkerStyle(22)
h_LcSt2ch_mbd_1pq_Mm_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1pq_Mm_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1pq_Mm_norm.SetMarkerColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm_norm.SetMarkerStyle(23)
h_LcSt2ch_mbd_1mq_Mm_norm.SetLineStyle(9)
h_LcSt2ch_mbd_1mq_Mm_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_1mq_Mm_norm.SetMarkerColor(r.kBlue)
d = c12.cd(1)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_q2_norm.GetBinContent(h_LcSt2ch_mbd_1pl_q2_norm.GetMaximumBin()), h_LcSt2ch_mbd_1ml_q2_norm.GetBinContent(h_LcSt2ch_mbd_1ml_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_q2_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1ml_q2_norm.DrawCopy('PE same')
h_startau_q2_norm.DrawCopy('PE hist same')
d = c12.cd(2)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_El_norm.GetBinContent(h_LcSt2ch_mbd_1pl_El_norm.GetMaximumBin()), h_LcSt2ch_mbd_1ml_El_norm.GetBinContent(h_LcSt2ch_mbd_1ml_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_El_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1ml_El_norm.DrawCopy('PE same')
h_startau_El_norm.DrawCopy('PE hist same')
d = c12.cd(3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pl_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1pl_Mm_norm.GetMaximumBin()), h_LcSt2ch_mbd_1ml_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1ml_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pl_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pl_Mm_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1ml_q2_norm.DrawCopy('PE same')
h_startau_Mm_norm.DrawCopy('PE hist same')
l12_1 = r.TLegend(0.1,0.7,0.4,0.9)
l12_1.AddEntry(h_startau_Mm_norm,'#Lambda*_{c} #tau','lP')
l12_1.AddEntry(h_LcSt2ch_mbd_1pl_Mm_norm,'#Lambda*_{c} X_{c} (#alpha_{l} = 1)','lP')
l12_1.AddEntry(h_LcSt2ch_mbd_1ml_Mm_norm,'#Lambda*_{c} X_{c} (#alpha_{l} = -1)','lP')
l11_1.Draw()
d = c12.cd(4)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_q2_norm.GetBinContent(h_LcSt2ch_mbd_1pq_q2_norm.GetMaximumBin()), h_LcSt2ch_mbd_1mq_q2_norm.GetBinContent(h_LcSt2ch_mbd_1mq_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_q2_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1mq_q2_norm.DrawCopy('PE same')
h_startau_q2_norm.DrawCopy('PE hist same')
d = c12.cd(5)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_El_norm.GetBinContent(h_LcSt2ch_mbd_1pq_El_norm.GetMaximumBin()), h_LcSt2ch_mbd_1mq_El_norm.GetBinContent(h_LcSt2ch_mbd_1mq_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_El_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1mq_El_norm.DrawCopy('PE same')
h_startau_El_norm.DrawCopy('PE hist same')
d = c12.cd(6)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_1pq_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1pq_Mm_norm.GetMaximumBin()), h_LcSt2ch_mbd_1mq_Mm_norm.GetBinContent(h_LcSt2ch_mbd_1mq_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_mbd_1pq_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_1pq_Mm_norm.DrawCopy('PE')
h_LcSt2ch_mbd_1mq_q2_norm.DrawCopy('PE same')
h_startau_Mm_norm.DrawCopy('PE hist same')
l12_2 = r.TLegend(0.1,0.7,0.4,0.9)
l12_2.AddEntry(h_startau_Mm_norm,'#Lambda*_{c} #tau','lP')
l12_2.AddEntry(h_LcSt2ch_mbd_1pq_Mm_norm,'#Lambda*_{c} X_{c} (#alpha_{q} = 1)','lP')
l12_2.AddEntry(h_LcSt2ch_mbd_1mq_Mm_norm,'#Lambda*_{c} X_{c} (#alpha_{q} = -1)','lP')
l12_2.Draw()

c13 = r.TCanvas('c13','c13: Comparison Lc*Xc and Lctau (TOP: 2body, BOT: mbody)',1500,1000)
c13.Divide(3,2)
h_LcSt2ch_2bd_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_2bd_Mm_norm.SetLineColor(r.kBlue)
h_tau_q2_norm.SetLineColor(r.kOrange-3)
h_tau_El_norm.SetLineColor(r.kOrange-3)
h_tau_Mm_norm.SetLineColor(r.kOrange-3)
d = c13.cd(1)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_q2_norm.GetBinContent(h_LcSt2ch_2bd_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_LcSt2ch_2bd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_q2_norm.DrawCopy('hist')
h_tau_q2_norm.DrawCopy('hist same')
d = c13.cd(2)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_El_norm.GetBinContent(h_LcSt2ch_2bd_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_LcSt2ch_2bd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_El_norm.DrawCopy('hist')
h_tau_El_norm.DrawCopy('hist same')
d = c13.cd(3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_2bd_Mm_norm.GetBinContent(h_LcSt2ch_2bd_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_2bd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_2bd_Mm_norm.DrawCopy('hist')
h_tau_Mm_norm.DrawCopy('hist same')
l13_1 = r.TLegend(0.1,0.7,0.4,0.9)
l13_1.AddEntry(h_LcSt2ch_2bd_Mm_norm,'#Lambda*_{c} X_{c} 2body')
l13_1.AddEntry(h_tau_Mm_norm,'#Lambda_{c}#tau')
l13_1.SetTextSize(0.04)
l13_1.Draw()
d = c13.cd(4)
h_LcSt2ch_mbd_q2_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_El_norm.SetLineColor(r.kBlue)
h_LcSt2ch_mbd_Mm_norm.SetLineColor(r.kBlue)
h_tau_q2_norm.SetLineColor(r.kOrange-3)
h_tau_El_norm.SetLineColor(r.kOrange-3)
h_tau_Mm_norm.SetLineColor(r.kOrange-3)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_q2_norm.GetBinContent(h_LcSt2ch_mbd_q2_norm.GetMaximumBin()),h_tau_q2_norm.GetBinContent(h_tau_q2_norm.GetMaximumBin())])
h_LcSt2ch_mbd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_q2_norm.DrawCopy('hist')
h_tau_q2_norm.DrawCopy('hist same')
d = c13.cd(5)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_El_norm.GetBinContent(h_LcSt2ch_mbd_El_norm.GetMaximumBin()),h_tau_El_norm.GetBinContent(h_tau_El_norm.GetMaximumBin())])
h_LcSt2ch_mbd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_El_norm.DrawCopy('hist')
h_tau_El_norm.DrawCopy('hist same')
d = c13.cd(6)
d.UseCurrentStyle()
ymax = max([h_LcSt2ch_mbd_Mm_norm.GetBinContent(h_LcSt2ch_mbd_Mm_norm.GetMaximumBin()),h_tau_Mm_norm.GetBinContent(h_tau_Mm_norm.GetMaximumBin())])
h_LcSt2ch_mbd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_LcSt2ch_mbd_Mm_norm.DrawCopy('hist')
h_tau_Mm_norm.DrawCopy('hist same')
l13_2 = r.TLegend(0.1,0.7,0.4,0.9)
l13_2.AddEntry(h_LcSt2ch_mbd_Mm_norm,'#Lambda*_{c} X_{c} mbody','l')
l13_2.AddEntry(h_tau_Mm_norm,'#Lambda_{c}#tau','l')
l13_2.SetTextSize(0.04)
l13_2.Draw()

c14 = r.TCanvas('c14','c14: Comparison LcXc and Lc*tau (TOP: 2body, BOT: mbody)',1500,1000)
c14.Divide(3,2)
h_Lc2ch_2bd_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_2bd_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_2bd_Mm_norm.SetLineColor(r.kBlue)
h_startau_q2_norm.SetLineColor(r.kOrange-3)
h_startau_El_norm.SetLineColor(r.kOrange-3)
h_startau_Mm_norm.SetLineColor(r.kOrange-3)
d = c14.cd(1)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_q2_norm.GetBinContent(h_Lc2ch_2bd_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_Lc2ch_2bd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_q2_norm.DrawCopy('hist')
h_startau_q2_norm.DrawCopy('hist same')
d = c14.cd(2)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_El_norm.GetBinContent(h_Lc2ch_2bd_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_Lc2ch_2bd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_El_norm.DrawCopy('hist')
h_startau_El_norm.DrawCopy('hist same')
d = c14.cd(3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_2bd_Mm_norm.GetBinContent(h_Lc2ch_2bd_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_Lc2ch_2bd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_2bd_Mm_norm.DrawCopy('hist')
h_startau_Mm_norm.DrawCopy('hist same')
l14_1 = r.TLegend(0.1,0.7,0.4,0.9)
l14_1.AddEntry(h_Lc2ch_2bd_Mm_norm,'#Lambda_{c} X_{c} 2body','l')
l14_1.AddEntry(h_startau_Mm_norm,'#Lambda*_{c}#tau','l')
l14_1.SetTextSize(0.04)
l14_1.Draw()
d = c14.cd(4)
h_Lc2ch_mbd_q2_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_El_norm.SetLineColor(r.kBlue)
h_Lc2ch_mbd_Mm_norm.SetLineColor(r.kBlue)
h_startau_q2_norm.SetLineColor(r.kOrange-3)
h_startau_El_norm.SetLineColor(r.kOrange-3)
h_startau_Mm_norm.SetLineColor(r.kOrange-3)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_q2_norm.GetBinContent(h_Lc2ch_mbd_q2_norm.GetMaximumBin()),h_startau_q2_norm.GetBinContent(h_startau_q2_norm.GetMaximumBin())])
h_Lc2ch_mbd_q2_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_q2_norm.DrawCopy('hist')
h_startau_q2_norm.DrawCopy('hist same')
d = c14.cd(5)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_El_norm.GetBinContent(h_Lc2ch_mbd_El_norm.GetMaximumBin()),h_startau_El_norm.GetBinContent(h_startau_El_norm.GetMaximumBin())])
h_Lc2ch_mbd_El_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_El_norm.DrawCopy('hist')
h_startau_El_norm.DrawCopy('hist same')
d = c14.cd(6)
d.UseCurrentStyle()
ymax = max([h_Lc2ch_mbd_Mm_norm.GetBinContent(h_Lc2ch_mbd_Mm_norm.GetMaximumBin()),h_startau_Mm_norm.GetBinContent(h_startau_Mm_norm.GetMaximumBin())])
h_Lc2ch_mbd_Mm_norm.GetYaxis().SetRangeUser(0,ymax+0.1*ymax)
h_Lc2ch_mbd_Mm_norm.DrawCopy('hist')
h_startau_Mm_norm.DrawCopy('hist same')
l14_2 = r.TLegend(0.1,0.7,0.4,0.9)
l14_2.AddEntry(h_Lc2ch_mbd_Mm_norm,'#Lambda_{c} X_{c} mbody','l')
l14_2.AddEntry(h_startau_Mm_norm,'#Lambda*_{c}#tau','l')
l14_2.SetTextSize(0.04)
l14_2.Draw()
